# permissions for end users to view delayedjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: delayedjob-viewer-role
rules:
- apiGroups:
  - batch.container-solutions.com
  resources:
  - delayedjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.container-solutions.com
  resources:
  - delayedjobs/status
  verbs:
  - get
