
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.container-solutions.com
  resources:
  - delayedjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.container-solutions.com
  resources:
  - delayedjobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.container-solutions.com
  resources:
  - delayedjobs/status
  verbs:
  - get
  - patch
  - update
