# Adds namespace to all resources.
namespace: default

bases:
  - ../crd
  - ../rbac
  - ../manager

patchesStrategicMerge:
  # Protect the /metrics endpoint by putting it behind auth.
  # If you want your controller-manager to expose the /metrics
  # endpoint w/o any authn/z, please comment the following line.
  - manager_auth_proxy_patch.yaml
